### ISSUE TITLE
Unrecognized LWP::UserAgent options: ssl_opts

### ISSUE THREAD

**Issue by MarcusCaepio** [regilero/check_phpfpm_status#15]
Hi,

just testing your Plugin and got one message on CLI:
Unrecognized LWP::UserAgent options: ssl_opts at ./check_phpfpm_status.pl line 224.

Hoe can I fix this? 
Running on Ubuntu 14.04
ii  liblwp-protocol-https-perl           6.04-2ubuntu0.1                     all          HTTPS driver for LWP::UserAgent

Regards,

Marcus

**Comment by regilero** [comment]
I made a change (untested) on a specific branch, can you try the script from this 'fix-old_lws' branch?
